### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: db.Connect is not a function

### ISSUE THREAD

**Issue by lawsonDevvv** [Tricky-Ricky/Contender#16] opened 2021-02-05 20:22 UTC
Triggered on line 46. Line contents: `bot.con = await db.Connect();`.

**Comment by N1GHTR4NG3R** [comment] 2021-02-06 04:24
Can you explain what you were doing before hand, and the steps you taken please. I don't see this on my end

**Comment by lawsonDevvv** [comment] 2021-02-06 14:49
I simply launched the bot after setting up my database as described in the description.

I tried changing the uppercase C to a lowercase c, then it gave an error smth about cant enqueue.

**Comment by lawsonDevvv** [comment] 2021-02-06 14:50
Im also getting a shit ton of module-not-found errors

**Comment by lawsonDevvv** [comment] 2021-02-06 15:07
According to my console, it's connecting to the database fine but throwing an error.

Error: Cannot enqueue Handshake after already enqueuing a Handshake.

**Comment by N1GHTR4NG3R** [comment] 2021-02-07 08:16
I am unable to reproduce this on my end.
Can you please give a detailed step by step of what you have done so far, and any further information you may think is necessary.
Thank you

**Comment by N1GHTR4NG3R** [comment] 2021-02-09 07:47
Will close this in 24hrs, as I'm unable to reproduce.

**Closed as completed** 2021-02-27 16:10 UTC
